<script setup lang="ts">
/** 人物详情页：头部信息（含内容类型徽标）+ 照片组 + 人脸注册 + 风格画像 + 素材瀑布流。
 *
 * 编排层：数据加载与业务逻辑在 composables/usePersonDetail 及人脸注册 composables，
 * 区块 UI 在 components/person/detail/ 子组件；本视图只做组装与事件接线。
 */

import { usePersonDetail } from '@/composables/usePersonDetail'
import { ref } from 'vue'
import { bloggersApi, modelsApi } from '@/api/persons'
import MasonryGrid from '@/components/inspiration/MasonryGrid.vue'
import ImageLightbox from '@/components/inspiration/ImageLightbox.vue'
import PersonFormModal from '@/components/person/PersonFormModal.vue'
import PersonDetailHeader from '@/components/person/detail/PersonDetailHeader.vue'
import PersonStyleProfile from '@/components/person/detail/PersonStyleProfile.vue'
import PersonPhotoSets from '@/components/person/detail/PersonPhotoSets.vue'
import PersonBloggerFaceRegister from '@/components/person/detail/PersonBloggerFaceRegister.vue'
import PersonModelFaceRegister from '@/components/person/detail/PersonModelFaceRegister.vue'
import PersonGroupCard from '@/components/person/detail/PersonGroupCard.vue'

const {
  personId,
  kind,
  kindLabel,
  detail,
  loading,
  isProfileUrlSafe,
  items,
  total,
  page,
  pageSize,
  itemsLoading,
  lightboxOpen,
  toInspirationOut,
  lightboxPaths,
  photoSets,
  photoSetsLoading,
  photoLightboxOpen,
  photoLightboxPaths,
  showForm,
  backToList,
  handleDelete,
  goSearchByTag,
  openPhotoSet,
  handleDeletePhotoSet,
  goAddPhotos,
  setPage,
  loadDetail,
  unbindOne,
  unbindAll,
  clearingAll,
} = usePersonDetail()

/** 详情页简介区域「AI 生成」入口：打开编辑弹窗并自动触发一次生成 */
const autoGenerateBio = ref(false)
function handleHeaderGenerateBio() {
  autoGenerateBio.value = true
  showForm.value = true
}
function onAutoGenerateDone() {
  autoGenerateBio.value = false
}

/** 人脸绑定变化（注册/注销）后刷新素材瀑布流与头部统计 */
async function onFaceChanged() {
  page.value = 1
  await Promise.all([loadDetail()])
}
</script>

<template>
  <div class="person-detail-page">
    <a-spin :loading="loading">
      <template v-if="detail">
        <!-- 面包屑 -->
        <a-breadcrumb style="margin-bottom: 16px">
          <a-breadcrumb-item @click="backToList">人物管理</a-breadcrumb-item>
          <a-breadcrumb-item>{{ detail.name }}</a-breadcrumb-item>
        </a-breadcrumb>

        <!-- 头部信息卡 -->
        <PersonDetailHeader
          :detail="detail"
          :kind="kind"
          :kind-label="kindLabel"
          :profile-url-safe="isProfileUrlSafe"
          @edit="showForm = true"
          @delete="handleDelete"
          @generate-bio="handleHeaderGenerateBio"
        />

        <!-- 人物组（方案 B）：同一现实人物跨平台账号（仅穿搭博主） -->
        <PersonGroupCard v-if="kind === 'blogger'" :person="detail" @changed="loadDetail" />

        <!-- 照片组（模特写真，仅职业模特展示；与穿搭素材分离） -->
        <PersonPhotoSets
          v-if="kind === 'model'"
          :photo-sets="photoSets"
          :loading="photoSetsLoading"
          @open="openPhotoSet"
          @delete="handleDeletePhotoSet"
          @add="goAddPhotos"
        />

        <!-- 人脸特征注册（模特：从照片组；博主：上传照片/素材选择） -->
        <PersonModelFaceRegister v-if="kind === 'model'" :person-id="personId" :api="modelsApi" />
        <PersonBloggerFaceRegister
          v-if="kind === 'blogger'"
          :person-id="personId"
          :api="bloggersApi"
          @changed="onFaceChanged"
        />

        <!-- 风格画像 -->
        <PersonStyleProfile :profile="detail.style_profile" @search-tag="goSearchByTag" />

        <!-- 素材瀑布流 -->
        <a-card size="small" class="items-card">
          <div class="items-header">
            <h3 style="margin: 0">TA 的素材</h3>
            <a-space>
              <a-button
                size="small"
                secondary
                :disabled="lightboxPaths.length === 0"
                @click="lightboxOpen = true"
              >
                🖼️ 全屏浏览
              </a-button>
              <!-- 清空全部绑定（仅博主）：保留人脸特征，解除全部素材归属 + 回退人脸记录 -->
              <a-popconfirm
                v-if="kind === 'blogger'"
                type="warning"
                :ok-loading="clearingAll"
                ok-text="确认清空"
                :ok-button-props="{ status: 'warning' }"
                @ok="unbindAll"
              >
                <template #content>
                  <div style="max-width: 300px">
                    将解除该博主与<b>全部 {{ total }} 个素材</b>的归属绑定，并把这些素材里识别为
                    该博主的人脸记录回退为「未匹配」（人脸扫描审核页可重新看到它们）。
                    <b>人脸特征会保留</b>，以后仍可自动匹配。此操作不可撤销。
                  </div>
                </template>
                <a-button
                  size="small"
                  status="warning"
                  :loading="clearingAll"
                  :disabled="total === 0"
                >
                  清空全部绑定
                </a-button>
              </a-popconfirm>
            </a-space>
          </div>

          <MasonryGrid
            :items="items.map(toInspirationOut)"
            :loading="itemsLoading"
            :show-actions="false"
            :show-unbind="kind === 'blogger'"
            unbind-tip="解除该素材与该博主的绑定？归属将移除、识别为该博主的人脸记录回退为未匹配。"
            empty-text="该人物还没有素材，去素材详情页关联或按博主采集吧"
            @unbind="unbindOne"
          />

          <a-pagination
            v-if="total > pageSize"
            style="margin-top: 16px; justify-content: flex-end"
            :current="page"
            :page-size="pageSize"
            :total="total"
            @change="setPage"
          />
        </a-card>

        <!-- 全屏灯箱：浏览该人物图片素材 -->
        <ImageLightbox
          :show="lightboxOpen"
          :image-paths="lightboxPaths"
          :initial-index="0"
          @close="lightboxOpen = false"
        />

        <!-- 全屏灯箱：浏览照片组照片 -->
        <ImageLightbox
          :show="photoLightboxOpen"
          :image-paths="photoLightboxPaths"
          :initial-index="0"
          @close="photoLightboxOpen = false"
        />
      </template>
    </a-spin>

    <!-- 编辑对话框 -->
    <PersonFormModal
      v-model:show="showForm"
      :kind="kind"
      :person="detail"
      :auto-generate-bio="autoGenerateBio"
      @auto-generate-done="onAutoGenerateDone"
      @saved="loadDetail()"
    />
  </div>
</template>

<style scoped>
.person-detail-page {
  max-width: 1200px;
  margin: 0 auto;
}

/* 素材区 */
.items-card {
  margin-bottom: 24px;
}

.items-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}
</style>
