[pytest]
testpaths = tests
asyncio_mode = auto
addopts = -q
filterwarnings =
    ignore:Please use `import python_multipart` instead:PendingDeprecationWarning
    ignore:Deprecated in 0\.9\.0:DeprecationWarning
    ignore:unclosed <class '.*Transport':ResourceWarning
    ignore:Exception ignored in:ResourceWarning
