"""baseline

Revision ID: 1aef95ac5977
Revises: 
Create Date: 2026-08-16 10:40:22.691317
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1aef95ac5977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """执行升级迁移。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('person_type', sa.String(length=16), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_person_type'), ['person_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_platform_user_id'), ['platform_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_source'), ['source'], unique=False)

    op.create_table('scraper_seen_urls',
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('source_url')
    )
    op.create_table('scraper_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_added', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('diagnostics', sa.Text(), nullable=True),
    sa.Column('resume_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraper_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraper_tasks_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraper_tasks_status'), ['status'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tags_pinned'), ['pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_source'), ['source'], unique=False)

    op.create_table('task_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_queue_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_queue_type'), ['type'], unique=False)

    op.create_table('inspirations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_author', sa.String(length=128), nullable=True),
    sa.Column('source_platform_id', sa.String(length=128), nullable=True),
    sa.Column('scraper_task_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('dominant_colors', sa.String(length=128), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.String(length=16), nullable=False),
    sa.Column('quality_reason', sa.Text(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('trash_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scraper_task_id'], ['scraper_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspirations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspirations_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspirations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspirations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspirations_is_ai_generated'), ['is_ai_generated'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspirations_quality_status'), ['quality_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspirations_scraper_task_id'), ['scraper_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspirations_source_platform_id'), ['source_platform_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspirations_source_type'), ['source_type'], unique=False)

    op.create_table('tag_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_aliases_alias'), ['alias'], unique=True)
        batch_op.create_index(batch_op.f('ix_tag_aliases_tag_id'), ['tag_id'], unique=False)

    op.create_table('ai_analysis_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspiration_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('log_type', sa.String(length=16), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspiration_id'], ['inspirations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_inspiration_id'), ['inspiration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_log_prompt_version'), ['prompt_version'], unique=False)

    op.create_table('inspiration_persons',
    sa.Column('inspiration_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inspiration_id'], ['inspirations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspiration_id', 'person_id'),
    sa.UniqueConstraint('inspiration_id', 'person_id', name='uq_inspiration_person')
    )
    with op.batch_alter_table('inspiration_persons', schema=None) as batch_op:
        batch_op.create_index('ix_inspiration_persons_person_id', ['person_id'], unique=False)

    op.create_table('inspiration_tags',
    sa.Column('inspiration_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inspiration_id'], ['inspirations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspiration_id', 'tag_id'),
    sa.UniqueConstraint('inspiration_id', 'tag_id', name='uq_inspiration_tag')
    )
    with op.batch_alter_table('inspiration_tags', schema=None) as batch_op:
        batch_op.create_index('ix_inspiration_tags_tag_id', ['tag_id'], unique=False)

    op.create_table('ai_extracted_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['ai_analysis_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_extracted_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_extracted_tags_log_id'), ['log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extracted_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('ai_quality_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['ai_analysis_log.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_quality_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_quality_review_log_id'), ['log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """执行降级迁移（回滚）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_quality_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_quality_review_log_id'))

    op.drop_table('ai_quality_review')
    with op.batch_alter_table('ai_extracted_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_extracted_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_ai_extracted_tags_log_id'))

    op.drop_table('ai_extracted_tags')
    with op.batch_alter_table('inspiration_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_inspiration_tags_tag_id')

    op.drop_table('inspiration_tags')
    with op.batch_alter_table('inspiration_persons', schema=None) as batch_op:
        batch_op.drop_index('ix_inspiration_persons_person_id')

    op.drop_table('inspiration_persons')
    with op.batch_alter_table('ai_analysis_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_prompt_version'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_model_version'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_log_inspiration_id'))

    op.drop_table('ai_analysis_log')
    with op.batch_alter_table('tag_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_aliases_tag_id'))
        batch_op.drop_index(batch_op.f('ix_tag_aliases_alias'))

    op.drop_table('tag_aliases')
    with op.batch_alter_table('inspirations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspirations_source_type'))
        batch_op.drop_index(batch_op.f('ix_inspirations_source_platform_id'))
        batch_op.drop_index(batch_op.f('ix_inspirations_scraper_task_id'))
        batch_op.drop_index(batch_op.f('ix_inspirations_quality_status'))
        batch_op.drop_index(batch_op.f('ix_inspirations_is_ai_generated'))
        batch_op.drop_index(batch_op.f('ix_inspirations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_inspirations_created_at'))
        batch_op.drop_index(batch_op.f('ix_inspirations_content_hash'))

    op.drop_table('inspirations')
    with op.batch_alter_table('task_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_queue_type'))
        batch_op.drop_index(batch_op.f('ix_task_queue_status'))
        batch_op.drop_index(batch_op.f('ix_task_queue_next_retry_at'))

    op.drop_table('task_queue')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_source'))
        batch_op.drop_index(batch_op.f('ix_tags_pinned'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_category'))

    op.drop_table('tags')
    with op.batch_alter_table('scraper_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraper_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_scraper_tasks_platform'))

    op.drop_table('scraper_tasks')
    op.drop_table('scraper_seen_urls')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_source'))
        batch_op.drop_index(batch_op.f('ix_persons_platform_user_id'))
        batch_op.drop_index(batch_op.f('ix_persons_platform'))
        batch_op.drop_index(batch_op.f('ix_persons_person_type'))
        batch_op.drop_index(batch_op.f('ix_persons_name'))
        batch_op.drop_index(batch_op.f('ix_persons_created_at'))

    op.drop_table('persons')
    # ### end Alembic commands ###
