"""新增定时采集计划表 scraper_schedules

Revision ID: e90015898fcd
Revises: 1aef95ac5977
Create Date: 2026-08-16 11:24:08.808352
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90015898fcd'
down_revision = '1aef95ac5977'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """执行升级迁移。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('sort_mode', sa.String(length=16), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_task_id', sa.Integer(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraper_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraper_schedules_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraper_schedules_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraper_schedules_platform'), ['platform'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """执行降级迁移（回滚）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraper_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraper_schedules_platform'))
        batch_op.drop_index(batch_op.f('ix_scraper_schedules_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_scraper_schedules_enabled'))

    op.drop_table('scraper_schedules')
    # ### end Alembic commands ###
